# Generated by Django 5.2.5 on 2026-02-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_remove_category_post_blogpost_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
